# coding: utf-8
# AUTOGENERATED BY gen_script.sh from kp1.py
# Copyright (C) Nyimbi Odero, Thu Aug  3 20:34:20 EAT 2017

from sqlalchemy import func
from flask_appbuilder import Model
from flask_appbuilder.models.mixins import AuditMixin, FileColumn, ImageColumn, UserExtensionMixin
from flask_appbuilder.models.decorators import renders
from flask_appbuilder.filemanager import ImageManager
from sqlalchemy_utils import aggregated, force_auto_coercion
from sqlalchemy.orm import relationship, query, defer, deferred

from sqlalchemy import (Column, Integer, String, ForeignKey,
    Sequence, Float, Text, BigInteger, Date,
    DateTime, Time, Boolean, CheckConstraint,
    UniqueConstraint, Numeric, LargeBinary , Table)
from datetime import timedelta, datetime, date
from sqlalchemy.dialects.postgresql import *
from sqlalchemy.sql import func
from .mixins import *

# Here is how to extend the User model
#class UserExtended(Model, UserExtensionMixin):
#    contact_group_id = Column(Integer, ForeignKey('contact_group.id'), nullable=True)
#    contact_group = relationship('ContactGroup')

# UTILITY CLASSES

import arrow, enum
import enum
# Initialize sqlalchemy_utils
#force_auto_coercion()




class Lawyer(AuditMixin, PersonMixin, ContactMixin, Model):
    __tablename__ = 'Lawyers'

    id = Column(Integer, primary_key=True, autoincrement=True)
    law_firm = Column(ForeignKey(u'lawfirm.id'), index=True)
    gender = Column(ForeignKey(u'gender.id'), index=True)
    barnumber = Column(String(20))

    gender1 = relationship(u'Gender', primaryjoin='Lawyer.gender == Gender.id', backref=u'lawyers')
    lawfirm = relationship(u'Lawfirm', primaryjoin='Lawyer.law_firm == Lawfirm.id', backref=u'lawyers')


class Policeman(AuditMixin, PersonMixin, ContactMixin, Model):
    __tablename__ = 'Policeman'

    id = Column(Integer, primary_key=True, autoincrement=True)
    police_rank = Column(ForeignKey(u'policerank.id'), nullable=False, index=True)
    gender = Column(ForeignKey(u'gender.id'), nullable=False, index=True)

    gender1 = relationship(u'Gender', primaryjoin='Policeman.gender == Gender.id', backref=u'policemen')
    policerank = relationship(u'Policerank', primaryjoin='Policeman.police_rank == Policerank.id', backref=u'policemen')
    policerole = relationship(u'Policerole', secondary='policeofficer_policerole', backref=u'policemen')


class Bail(AuditMixin, Model):
    __tablename__ = 'bail'

    id = Column(Integer, primary_key=True, autoincrement=True)
    hearing = Column(ForeignKey(u'hearing.id'), nullable=False, index=True)
    defendant = Column(ForeignKey(u'defendant.id'), nullable=False, index=True)
    amountgranted = Column(Numeric(12, 2))
    noofsureties = Column(Integer, nullable=False)
    paid = Column(Boolean)
    paydate = Column(Date)

    defendant1 = relationship(u'Defendant', primaryjoin='Bail.defendant == Defendant.id', backref=u'bails')
    hearing1 = relationship(u'Hearing', primaryjoin='Bail.hearing == Hearing.id', backref=u'bails')
    surety = relationship(u'Surety', secondary='bail_surety', backref=u'bails')


bail_surety = Table(
    'bail_surety', Model.metadata,
    Column('bail', ForeignKey(u'bail.id'), primary_key=True, nullable=False),
    Column('surety', ForeignKey(u'surety.id'), primary_key=True, nullable=False, index=True)
)


class Case(AuditMixin, Model):
    __tablename__ = 'case'

    id = Column(Integer, primary_key=True, autoincrement=True)
    casename = Column(String(200), nullable=False)
    docketnumber = Column(String(100))
    investigationassigmentdate = Column(DateTime)
    investigationassignmentnote = Column(Text, nullable=False)
    investigationplan = Column(Text, nullable=False)
    initialreport = Column(Text, nullable=False)
    priority = Column(Integer, nullable=False)
    investigationsummary = Column(Text, nullable=False)
    agadvicerequested = Column(Boolean)
    sendtotrial = Column(Boolean, nullable=False)
    nameofcase = Column(String(400))
    chargedate = Column(DateTime)
    agadvice = Column(Text, nullable=False)
    taketotrial = Column(Boolean, nullable=False)
    caseclosed = Column(Boolean)
    judgement = Column(Text, nullable=False)
    closeddate = Column(Date)
    sentencelength = Column(Integer)
    sentencestartdate = Column(Date)
    sentenceexpirydate = Column(Date)
    fineamount = Column(Numeric(10,2))
    caseappealed = Column(Boolean)
    appealdate = Column(DateTime)

    policestation = relationship(u'Policestation', secondary='case_policestation', backref=u'cases')
    natureofsuit = relationship(u'Natureofsuit', secondary='case_natureofsuit', backref=u'cases')
    plaintiff = relationship(u'Plaintiff', secondary='case_plaintiff', backref=u'cases')
    prosecutor = relationship(u'Prosecutor', secondary='case_prosecutor', backref=u'cases')
    witness = relationship(u'Witnes', secondary='case_witness', backref=u'cases')
    Policeman = relationship(u'Policeman', secondary='case_policeofficer', backref=u'policeman_cases')
    Policeman1 = relationship(u'Policeman', secondary='case_policeofficer_2', backref=u'policeman_cases_0')
    casecategory = relationship(u'Casecategory', secondary='case_casecategory', backref=u'cases')
    defendant = relationship(u'Defendant', secondary='case_defendant', backref=u'cases')
    causeofaction = relationship(u'Causeofaction', secondary='case_causeofaction', backref=u'cases')


case_casecategory = Table(
    'case_casecategory', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('casecategory', ForeignKey(u'casecategory.id'), primary_key=True, nullable=False, index=True)
)


case_causeofaction = Table(
    'case_causeofaction', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('causeofaction', ForeignKey(u'causeofaction.id'), primary_key=True, nullable=False, index=True)
)


case_defendant = Table(
    'case_defendant', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('defendant', ForeignKey(u'defendant.id'), primary_key=True, nullable=False, index=True)
)


case_natureofsuit = Table(
    'case_natureofsuit', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('natureofsuit', ForeignKey(u'natureofsuit.id'), primary_key=True, nullable=False, index=True)
)


case_plaintiff = Table(
    'case_plaintiff', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('plaintiff', ForeignKey(u'plaintiff.id'), primary_key=True, nullable=False, index=True)
)


case_policeofficer = Table(
    'case_policeofficer', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('policeofficer', ForeignKey(u'Policeman.id'), primary_key=True, nullable=False, index=True)
)


case_policeofficer_2 = Table(
    'case_policeofficer_2', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('policeofficer', ForeignKey(u'Policeman.id'), primary_key=True, nullable=False, index=True)
)


case_policestation = Table(
    'case_policestation', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('policestation', ForeignKey(u'policestation.id'), primary_key=True, nullable=False, index=True)
)


case_prosecutor = Table(
    'case_prosecutor', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('prosecutor', ForeignKey(u'prosecutor.id'), primary_key=True, nullable=False, index=True)
)


case_witness = Table(
    'case_witness', Model.metadata,
    Column('case', ForeignKey(u'case.id'), primary_key=True, nullable=False),
    Column('witness', ForeignKey(u'witness.id'), primary_key=True, nullable=False, index=True)
)


class Casecategory(AuditMixin, Model):
    __tablename__ = 'casecategory'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Causeofaction(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'causeofaction'

    id = Column(Integer, primary_key=True, autoincrement=True)
    criminal = Column(Boolean, nullable=False)
    parent_coa = Column(ForeignKey(u'causeofaction.id'), index=True)

    parent = relationship(u'Causeofaction', remote_side=[id], primaryjoin='Causeofaction.parent_coa == Causeofaction.id', backref=u'causeofactions')
    filing = relationship(u'Filing', secondary='causeofaction_filing', backref=u'causeofactions')
    hearing = relationship(u'Hearing', secondary='causeofaction_hearing', backref=u'causeofactions')


causeofaction_filing = Table(
    'causeofaction_filing', Model.metadata,
    Column('causeofaction', ForeignKey(u'causeofaction.id'), primary_key=True, nullable=False),
    Column('filing', ForeignKey(u'filing.id'), primary_key=True, nullable=False, index=True)
)


causeofaction_hearing = Table(
    'causeofaction_hearing', Model.metadata,
    Column('causeofaction', ForeignKey(u'causeofaction.id'), primary_key=True, nullable=False),
    Column('hearing', ForeignKey(u'hearing.id'), primary_key=True, nullable=False, index=True)
)


class Commitaltype(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'commitaltype'

    id = Column(Integer, primary_key=True, autoincrement=True)

    prisoncommital = relationship(u'Prisoncommital', secondary='commitaltype_prisoncommital', backref=u'commitaltypes')


commitaltype_prisoncommital = Table(
    'commitaltype_prisoncommital', Model.metadata,
    Column('commitaltype', ForeignKey(u'commitaltype.id'), primary_key=True, nullable=False),
    Column('prisoncommital_prison', Integer, primary_key=True, nullable=False),
    Column('prisoncommital_warrantno', String(100), primary_key=True, nullable=False),
    ForeignKeyConstraint(['prisoncommital_prison', 'prisoncommital_warrantno'], [u'prisoncommital.prison', u'prisoncommital.warrantno']),
    Index('idx_commitaltype_prisoncommital', 'prisoncommital_prison', 'prisoncommital_warrantno')
)


class Constituency(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'constituency'

    id = Column(Integer, primary_key=True, autoincrement=True)
    county = Column(ForeignKey(u'county.id'), nullable=False, index=True)
    town = Column(ForeignKey(u'town.id'), index=True)

    county1 = relationship(u'County', primaryjoin='Constituency.county == County.id', backref=u'constituencies')
    town1 = relationship(u'Town', primaryjoin='Constituency.town == Town.id', backref=u'constituencies')


class County(AuditMixin, Model):
    __tablename__ = 'county'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Court(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'court'

    id = Column(Integer, primary_key=True, autoincrement=True)
    court_station = Column(ForeignKey(u'courtstation.id'), nullable=False, index=True)

    courtstation = relationship(u'Courtstation', primaryjoin='Court.court_station == Courtstation.id', backref=u'courts')


class Courtlevel(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'courtlevel'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Courtstation(AuditMixin, Model):
    __tablename__ = 'courtstation'

    id = Column(Integer, primary_key=True, autoincrement=True)
    residentmagistrate = Column(String(100))
    registrar = Column(String(100), nullable=False)
    court_level = Column(ForeignKey(u'courtlevel.id'), nullable=False, index=True)
    num_of_courts = Column(Integer)
    town = Column(ForeignKey(u'town.id'), nullable=False, index=True)

    courtlevel = relationship(u'Courtlevel', primaryjoin='Courtstation.court_level == Courtlevel.id', backref=u'courtstations')
    town1 = relationship(u'Town', primaryjoin='Courtstation.town == Town.id', backref=u'courtstations')


class Defendant(BiometricMixin, EmploymentMixin, PersonMixin, ContactMixin,  AuditMixin, Model):
    __tablename__ = 'defendant'

    def ViewName(self):
        return self.__class__.__name__ +'View'

    def photo_img(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')

    def photo_img_thumbnail(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url_thumbnail(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')


    def print_button(self):
        vn = self.ViewName()
        #pdf = render_pdf(url_for(vn, pk=str(self.id)))
        #pdf = pdfkit.from_string(url_for(vn, pk=str(self.id)))
        #response = make_response(pdf)
        #response.headers['Content-Type'] = 'application/pdf'
        #response.headers['Content-Disposition'] = 'inline; filename=output.pdf'

        return Markup(
            '<a href="' + url_for(vn) + '" class="btn btn-sm btn-primary" data-toggle="tooltip" rel="tooltip"'+
            'title="Print">' +
            '<i class="fa fa-edit"></i>' +
            '</a>')

    def audio_play(self):
        vn = self.ViewName()
        return Markup(
                "<audio controls>
                '<source  src="' + url_for(vn) + '" type="audio/mpeg"'> +'<i class="fa fa-volume-up"></i>' +
                'Your browser does not support the audio element.'
                '</audio>"
                )
    # edit_form_extra_fields = {'field2': TextField('field2',
    #                             widget=BS3TextFieldROWidget())}
    id = Column(Integer, primary_key=True, autoincrement=True)
    gender = Column(ForeignKey(u'gender.id'), nullable=False, index=True)

    gender1 = relationship(u'Gender', primaryjoin='Defendant.gender == Gender.id', backref=u'defendants')
    hearing = relationship(u'Hearing', secondary='defendant_hearing', backref=u'defendants')


defendant_hearing = Table(
    'defendant_hearing', Model.metadata,
    Column('defendant', ForeignKey(u'defendant.id'), primary_key=True, nullable=False),
    Column('hearing', ForeignKey(u'hearing.id'), primary_key=True, nullable=False, index=True)
)


class Doctemplate(DocMixin, RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'doctemplate'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Document(DocMixin, AuditMixin, Model):
    __tablename__ = 'document'

    id = Column(Integer, primary_key=True, autoincrement=True)
    doc_template = Column(ForeignKey(u'doctemplate.id'), index=True)

    doctemplate = relationship(u'Doctemplate', primaryjoin='Document.doc_template == Doctemplate.id', backref=u'documents')
    filing = relationship(u'Filing', secondary='document_filing', backref=u'documents')


document_filing = Table(
    'document_filing', Model.metadata,
    Column('document', ForeignKey(u'document.id'), primary_key=True, nullable=False),
    Column('filing', ForeignKey(u'filing.id'), primary_key=True, nullable=False, index=True)
)


class Filing(AuditMixin, Model):
    __tablename__ = 'filing'

    id = Column(Integer, primary_key=True, autoincrement=True)
    uploaddate = Column(DateTime)
    pages = Column(Integer)
    totalfees = Column(Numeric(12, 2), nullable=False)
    filing_attorney = Column(ForeignKey(u'Lawyers.id'), nullable=False, index=True)
    filing_prosecutor = Column(ForeignKey(u'prosecutor.id'), nullable=False, index=True)
    assessedfees = Column(Numeric(12, 2))
    receiptverified = Column(Boolean)
    amountpaid = Column(Numeric(12, 2))
    feebalance = Column(Numeric(12, 2))
    paymenthistory = Column(Text, nullable=False)
    case = Column(ForeignKey(u'case.id'), nullable=False, index=True)

    case1 = relationship(u'Case', primaryjoin='Filing.case == Case.id', backref=u'filings')
    Lawyer = relationship(u'Lawyer', primaryjoin='Filing.filing_attorney == Lawyer.id', backref=u'filings')
    prosecutor = relationship(u'Prosecutor', primaryjoin='Filing.filing_prosecutor == Prosecutor.id', backref=u'filings')
    filingtype = relationship(u'Filingtype', secondary='filing_filingtype', backref=u'filings')
    payment = relationship(u'Payment', secondary='filing_payment', backref=u'filings')


filing_filingtype = Table(
    'filing_filingtype', Model.metadata,
    Column('filing', ForeignKey(u'filing.id'), primary_key=True, nullable=False),
    Column('filingtype', ForeignKey(u'filingtype.id'), primary_key=True, nullable=False, index=True)
)


filing_payment = Table(
    'filing_payment', Model.metadata,
    Column('filing', ForeignKey(u'filing.id'), primary_key=True, nullable=False),
    Column('payment', ForeignKey(u'payment.id'), primary_key=True, nullable=False, index=True)
)


class Filingtype(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'filingtype'

    id = Column(Integer, primary_key=True, autoincrement=True)
    fees = Column(Numeric(12, 2), nullable=False)
    perpagecost = Column(Numeric(12, 2))
    paid_per_page = Column(Boolean)


class Gender(AuditMixin, Model):
    __tablename__ = 'gender'

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(20), nullable=False, unique=True)


class Hearing(ActivityMixin, AuditMixin, Model):
    __tablename__ = 'hearing'

    id = Column(Integer, primary_key=True, autoincrement=True)
    hearingdate = Column(DateTime, nullable=False)
    adjourned = Column(Boolean)
    case = Column(ForeignKey(u'case.id'), nullable=False, index=True)
    court = Column(ForeignKey(u'court.id'), nullable=False, index=True)
    remandwarrant = Column(Text, nullable=False)
    hearing_type = Column(ForeignKey(u'hearingtype.id'), nullable=False, index=True)
    remandlength = Column(Integer)
    remanddate = Column(Date)
    remandwarrantexpirydate = Column(Date)
    nexthearingdate = Column(Date)
    finalhearing = Column(Boolean, nullable=False)
    transcript = Column(Text, nullable=False)
    audio = Column(LargeBinary)
    video = Column(LargeBinary)

    case1 = relationship(u'Case', primaryjoin='Hearing.case == Case.id', backref=u'hearings')
    court1 = relationship(u'Court', primaryjoin='Hearing.court == Court.id', backref=u'hearings')
    hearingtype = relationship(u'Hearingtype', primaryjoin='Hearing.hearing_type == Hearingtype.id', backref=u'hearings')
    prosecutor = relationship(u'Prosecutor', secondary='hearing_prosecutor', backref=u'hearings')
    Policeman = relationship(u'Policeman', secondary='hearing_policeofficer', backref=u'hearings')
    witness = relationship(u'Witnes', secondary='hearing_witness', backref=u'hearings')
    Lawyers = relationship(u'Lawyer', secondary='hearing_lawyer', backref=u'hearings')
    judicialofficer = relationship(u'Judicialofficer', secondary='hearing_judicialofficer', backref=u'hearings')


hearing_judicialofficer = Table(
    'hearing_judicialofficer', Model.metadata,
    Column('hearing', ForeignKey(u'hearing.id'), primary_key=True, nullable=False),
    Column('judicialofficer', ForeignKey(u'judicialofficer.id'), primary_key=True, nullable=False, index=True)
)


hearing_lawyer = Table(
    'hearing_lawyer', Model.metadata,
    Column('hearing', ForeignKey(u'hearing.id'), primary_key=True, nullable=False),
    Column('lawyer', ForeignKey(u'Lawyers.id'), primary_key=True, nullable=False, index=True)
)


hearing_policeofficer = Table(
    'hearing_policeofficer', Model.metadata,
    Column('hearing', ForeignKey(u'hearing.id'), primary_key=True, nullable=False),
    Column('policeofficer', ForeignKey(u'Policeman.id'), primary_key=True, nullable=False, index=True)
)


hearing_prosecutor = Table(
    'hearing_prosecutor', Model.metadata,
    Column('hearing', ForeignKey(u'hearing.id'), primary_key=True, nullable=False),
    Column('prosecutor', ForeignKey(u'prosecutor.id'), primary_key=True, nullable=False, index=True)
)


hearing_witness = Table(
    'hearing_witness', Model.metadata,
    Column('hearing', ForeignKey(u'hearing.id'), primary_key=True, nullable=False),
    Column('witness', ForeignKey(u'witness.id'), primary_key=True, nullable=False, index=True)
)


class Hearingtype(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'hearingtype'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Investigation(AuditMixin, Model):
    __tablename__ = 'investigation'

    id = Column(Integer, primary_key=True, autoincrement=True)
    case = Column(ForeignKey(u'case.id'), nullable=False, index=True)
    actiondate = Column(DateTime, nullable=False)
    evidence = Column(Text, nullable=False)
    narrative = Column(Text, nullable=False)
    weather = Column(Text, nullable=False)
    location = Column(Text, nullable=False)

    case1 = relationship(u'Case', primaryjoin='Investigation.case == Case.id', backref=u'investigations')
    Policeman = relationship(u'Policeman', secondary='investigation_policeofficer', backref=u'investigations')
    witness = relationship(u'Witnes', secondary='investigation_witness', backref=u'investigations')


investigation_policeofficer = Table(
    'investigation_policeofficer', Model.metadata,
    Column('investigation', ForeignKey(u'investigation.id'), primary_key=True, nullable=False),
    Column('policeofficer', ForeignKey(u'Policeman.id'), primary_key=True, nullable=False, index=True)
)


investigation_witness = Table(
    'investigation_witness', Model.metadata,
    Column('investigation', ForeignKey(u'investigation.id'), primary_key=True, nullable=False),
    Column('witness', ForeignKey(u'witness.id'), primary_key=True, nullable=False, index=True)
)


class JoRank(AuditMixin, Model):
    __tablename__ = 'jo_rank'

    id = Column(Integer, primary_key=True, autoincrement=True)
    appelation = Column(Text, nullable=False)
    informaladdress = Column(Text, nullable=False)


class Judicialofficer(PersonMixin, ContactMixin,  AuditMixin, Model):
    __tablename__ = 'judicialofficer'

    def ViewName(self):
        return self.__class__.__name__ +'View'

    def photo_img(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')

    def photo_img_thumbnail(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url_thumbnail(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')


    def print_button(self):
        vn = self.ViewName()
        #pdf = render_pdf(url_for(vn, pk=str(self.id)))
        #pdf = pdfkit.from_string(url_for(vn, pk=str(self.id)))
        #response = make_response(pdf)
        #response.headers['Content-Type'] = 'application/pdf'
        #response.headers['Content-Disposition'] = 'inline; filename=output.pdf'

        return Markup(
            '<a href="' + url_for(vn) + '" class="btn btn-sm btn-primary" data-toggle="tooltip" rel="tooltip"'+
            'title="Print">' +
            '<i class="fa fa-edit"></i>' +
            '</a>')

    def audio_play(self):
        vn = self.ViewName()
        return Markup(
                '<audio controls>' +
                '<source  src="' + url_for(vn) + '" type="audio/mpeg"'> +'<i class="fa fa-volume-up"></i>' +
                'Your browser does not support the audio element.' +
                '</audio>'
                )
    # edit_form_extra_fields = {'field2': TextField('field2',
    #                             widget=BS3TextFieldROWidget())}
    id = Column(Integer, primary_key=True, autoincrement=True)
    j_o__rank = Column(ForeignKey(u'jo_rank.id'), nullable=False, index=True)
    gender = Column(ForeignKey(u'gender.id'), index=True)
    court = Column(ForeignKey(u'court.id'), nullable=False, index=True)

    court1 = relationship(u'Court', primaryjoin='Judicialofficer.court == Court.id', backref=u'judicialofficers')
    gender1 = relationship(u'Gender', primaryjoin='Judicialofficer.gender == Gender.id', backref=u'judicialofficers')
    jo_rank = relationship(u'JoRank', primaryjoin='Judicialofficer.j_o__rank == JoRank.id', backref=u'judicialofficers')


class Lawfirm(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'lawfirm'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Natureofsuit(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'natureofsuit'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Payment(AuditMixin, Model):
    __tablename__ = 'payment'

    id = Column(Integer, primary_key=True, autoincrement=True)
    amountpaid = Column(Numeric(12, 2))
    datepaid = Column(DateTime)
    paymentreference = Column(String(80), nullable=False)
    paymentconfirmed = Column(Boolean)
    paidby = Column(Text, nullable=False)
    msisdn = Column(Text)
    receiptnumber = Column(String(100), nullable=False)
    ispartial = Column(Boolean)
    bail = Column(ForeignKey(u'bail.id'), index=True)
    billrefnumber = Column(Text, nullable=False)
    payment_method = Column(ForeignKey(u'paymentmethod.id'), nullable=False, index=True)
    paymentdescription = Column(Text, nullable=False)

    bail1 = relationship(u'Bail', primaryjoin='Payment.bail == Bail.id', backref=u'payments')
    paymentmethod = relationship(u'Paymentmethod', primaryjoin='Payment.payment_method == Paymentmethod.id', backref=u'payments')


class Paymentmethod(AuditMixin, Model):
    __tablename__ = 'paymentmethod'

    id = Column(Integer, primary_key=True, autoincrement=True)
    key = Column(Text, nullable=False)
    secret = Column(Text, nullable=False)
    portal = Column(Text, nullable=False)
    tillnumber = Column(Text, nullable=False)
    shortcode = Column(Text, nullable=False)


class Plaintiff(PersonMixin, ContactMixin,  AuditMixin, Model):
    __tablename__ = 'plaintiff'

    def ViewName(self):
        return self.__class__.__name__ +'View'

    def photo_img(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')

    def photo_img_thumbnail(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url_thumbnail(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')


    def print_button(self):
        vn = self.ViewName()
        #pdf = render_pdf(url_for(vn, pk=str(self.id)))
        #pdf = pdfkit.from_string(url_for(vn, pk=str(self.id)))
        #response = make_response(pdf)
        #response.headers['Content-Type'] = 'application/pdf'
        #response.headers['Content-Disposition'] = 'inline; filename=output.pdf'

        return Markup(
            '<a href="' + url_for(vn) + '" class="btn btn-sm btn-primary" data-toggle="tooltip" rel="tooltip"'+
            'title="Print">' +
            '<i class="fa fa-edit"></i>' +
            '</a>')

    def audio_play(self):
        vn = self.ViewName()
        return Markup(
                <audio controls>
                '<source  src="' + url_for(vn) + '" type="audio/mpeg"'> +'<i class="fa fa-volume-up"></i>' +
                'Your browser does not support the audio element.'
                '</audio>
                )
    # edit_form_extra_fields = {'field2': TextField('field2',
    #                             widget=BS3TextFieldROWidget())}
    id = Column(Integer, primary_key=True, autoincrement=True)
    gender = Column(ForeignKey(u'gender.id'), index=True)

    gender1 = relationship(u'Gender', primaryjoin='Plaintiff.gender == Gender.id', backref=u'plaintiffs')


policeofficer_policerole = Table(
    'policeofficer_policerole', Model.metadata,
    Column('policeofficer', ForeignKey(u'Policeman.id'), primary_key=True, nullable=False),
    Column('policerole', ForeignKey(u'policerole.id'), primary_key=True, nullable=False, index=True)
)


class Policerank(AuditMixin, Model):
    __tablename__ = 'policerank'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Policerole(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'policerole'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Policestation(AuditMixin, Model):
    __tablename__ = 'policestation'

    id = Column(Integer, primary_key=True, autoincrement=True)
    town = Column(ForeignKey(u'town.id'), nullable=False, index=True)
    officercommanding = Column(String(100))
    police_station_type = Column(ForeignKey(u'policestationtype.id'), nullable=False, index=True)

    policestationtype = relationship(u'Policestationtype', primaryjoin='Policestation.police_station_type == Policestationtype.id', backref=u'policestations')
    town1 = relationship(u'Town', primaryjoin='Policestation.town == Town.id', backref=u'policestations')


class Policestationtype(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'policestationtype'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Prison(AuditMixin, Model):
    __tablename__ = 'prison'

    id = Column(Integer, primary_key=True, autoincrement=True)
    town = Column(ForeignKey(u'town.id'), nullable=False, index=True)
    warden = Column(String(100))
    capacity = Column(Integer)
    population = Column(Integer)

    town1 = relationship(u'Town', primaryjoin='Prison.town == Town.id', backref=u'prisons')


class Prisoncommital(AuditMixin, Model):
    __tablename__ = 'prisoncommital'

    prison = Column(ForeignKey(u'prison.id'), primary_key=True, nullable=False)
    warrantno = Column(String(100), primary_key=True, nullable=False)
    defendant = Column(ForeignKey(u'defendant.id'), nullable=False, index=True)
    hearing = Column(ForeignKey(u'hearing.id'), nullable=False, index=True)
    warrantduration = Column(Integer, nullable=False)
    warrantdate = Column(DateTime)
    warrant = Column(Text, nullable=False)
    warrantexpiry = Column(DateTime, nullable=False)
    history = Column(Text, nullable=False)
    earliestrelease = Column(Date)

    defendant1 = relationship(u'Defendant', primaryjoin='Prisoncommital.defendant == Defendant.id', backref=u'prisoncommitals')
    hearing1 = relationship(u'Hearing', primaryjoin='Prisoncommital.hearing == Hearing.id', backref=u'prisoncommitals')
    prison1 = relationship(u'Prison', primaryjoin='Prisoncommital.prison == Prison.id', backref=u'prisoncommitals')


class Prosecutor(PersonMixin, ContactMixin,  AuditMixin, Model):
    __tablename__ = 'prosecutor'

    def ViewName(self):
        return self.__class__.__name__ +'View'

    def photo_img(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')

    def photo_img_thumbnail(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url_thumbnail(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')


    def print_button(self):
        vn = self.ViewName()
        #pdf = render_pdf(url_for(vn, pk=str(self.id)))
        #pdf = pdfkit.from_string(url_for(vn, pk=str(self.id)))
        #response = make_response(pdf)
        #response.headers['Content-Type'] = 'application/pdf'
        #response.headers['Content-Disposition'] = 'inline; filename=output.pdf'

        return Markup(
            '<a href="' + url_for(vn) + '" class="btn btn-sm btn-primary" data-toggle="tooltip" rel="tooltip"'+
            'title="Print">' +
            '<i class="fa fa-edit"></i>' +
            '</a>')

    def audio_play(self):
        vn = self.ViewName()
        return Markup(
                <audio controls>
                '<source  src="' + url_for(vn) + '" type="audio/mpeg"'> +'<i class="fa fa-volume-up"></i>' +
                'Your browser does not support the audio element.'
                '</audio>
                )
    # edit_form_extra_fields = {'field2': TextField('field2',
    #                             widget=BS3TextFieldROWidget())}
    id = Column(Integer, primary_key=True, autoincrement=True)
    gender = Column(ForeignKey(u'gender.id'), index=True)

    gender1 = relationship(u'Gender', primaryjoin='Prosecutor.gender == Gender.id', backref=u'prosecutors')
    prosecutorteam = relationship(u'Prosecutorteam', secondary='prosecutor_prosecutorteam', backref=u'prosecutors')


prosecutor_prosecutorteam = Table(
    'prosecutor_prosecutorteam', Model.metadata,
    Column('prosecutor', ForeignKey(u'prosecutor.id'), primary_key=True, nullable=False),
    Column('prosecutorteam', ForeignKey(u'prosecutorteam.id'), primary_key=True, nullable=False, index=True)
)


class Prosecutorteam(AuditMixin, Model):
    __tablename__ = 'prosecutorteam'

    id = Column(Integer, primary_key=True, autoincrement=True)


class Subcounty(AuditMixin, Model):
    __tablename__ = 'subcounty'

    id = Column(Integer, primary_key=True, autoincrement=True)
    county = Column(ForeignKey(u'county.id'), nullable=False, index=True)

    county1 = relationship(u'County', primaryjoin='Subcounty.county == County.id', backref=u'subcounties')


class Surety(PersonMixin, ContactMixin,  AuditMixin, Model):
    __tablename__ = 'surety'

    def ViewName(self):
        return self.__class__.__name__ +'View'

    def photo_img(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')

    def photo_img_thumbnail(self):
        im = ImageManager()
        vn = self.ViewName()
        if self.photo:
            return Markup('<a href="' + url_for(vn+'.show', pk=str(self.id)) +
                        '" class="thumbnail"><img src="' + im.get_url_thumbnail(self.photo) +
                        '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for(vn, pk=str(self.id)) +
                        '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')


    def print_button(self):
        vn = self.ViewName()
        #pdf = render_pdf(url_for(vn, pk=str(self.id)))
        #pdf = pdfkit.from_string(url_for(vn, pk=str(self.id)))
        #response = make_response(pdf)
        #response.headers['Content-Type'] = 'application/pdf'
        #response.headers['Content-Disposition'] = 'inline; filename=output.pdf'

        return Markup(
            '<a href="' + url_for(vn) + '" class="btn btn-sm btn-primary" data-toggle="tooltip" rel="tooltip"'+
            'title="Print">' +
            '<i class="fa fa-edit"></i>' +
            '</a>')

    def audio_play(self):
        vn = self.ViewName()
        return Markup(
                <audio controls>
                '<source  src="' + url_for(vn) + '" type="audio/mpeg"'> +'<i class="fa fa-volume-up"></i>' +
                'Your browser does not support the audio element.'
                '</audio>
                )
    # edit_form_extra_fields = {'field2': TextField('field2',
    #                             widget=BS3TextFieldROWidget())}
    id = Column(Integer, primary_key=True, autoincrement=True)
    gender = Column(ForeignKey(u'gender.id'), index=True)

    gender1 = relationship(u'Gender', primaryjoin='Surety.gender == Gender.id', backref=u'sureties')


class Town(RefTypeMixin, AuditMixin, Model):
    __tablename__ = 'town'

    id = Column(Integer, primary_key=True, autoincrement=True)
    subcounty = Column(ForeignKey(u'subcounty.id'), nullable=False, index=True)

    subcounty1 = relationship(u'Subcounty', primaryjoin='Town.subcounty == Subcounty.id', backref=u'towns')


class Witnes(AuditMixin, Model):
    __tablename__ = 'witness'

    id = Column(Integer, primary_key=True, autoincrement=True)
    fordefense = Column(Boolean)
    gender = Column(ForeignKey(u'gender.id'), nullable=False, index=True)

    gender1 = relationship(u'Gender', primaryjoin='Witnes.gender == Gender.id', backref=u'witness')
